# Generated by Django 4.2.2 on 2023-08-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_photos/Smiling-Penguin.png', null=True, upload_to='profile_photos/'),
        ),
    ]
