# Generated by Django 4.2.2 on 2023-08-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
    ]
